version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dodo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: dodo
      POSTGRES_PASSWORD: mydodopassword
    ports:
      - "6666:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dodo -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
